### ISSUE TITLE
error while loading elm_show_type.py

### ISSUE THREAD

**Issue by adriantofan** [deadfoxygrandpa/Elm.tmLanguage#91]
Hello, 

When starting sublimetext 2 I got the following error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./elm_show_type.py", line 133
    for v in data 
      ^
SyntaxError: invalid syntax
```

This means that show type command is always disabled. Can you help me fix this ?

Thank you

**Comment by adriantofan** [comment]
I forgot to tell you that I am using ST 2.

In the mean time I've installed Sublime Text 3 with Elm syntax higgling. I've got other errors complaining about the output of elm-make and elm-oracle. 

Next thing I configured package manager to use the beta repository and now it seems to be working.

I am not sure if this is normal given evolutions of the tools.

**Comment by nmehta6** [comment]
I am having an issue with `elm_show_type.py` as well. I am not sure if the root cause is the same as your issue @adriantofan. Here is what I get:

```
Error loading scope:source.glsl: Unable to find syntax file for scope source.glsl in Packages/Elm Language Support/Syntaxes/Elm.tmLanguage
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 333, in on_activated_async
    callback.on_activated_async(v)
  File "/Users/nachiketmehta/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 226, in on_activated_async
    view_load(view)
  File "/Users/nachiketmehta/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 210, in view_load
    load_from_oracle(view.file_name())
  File "/Users/nachiketmehta/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_show_type.py", line 184, in load_from_oracle
    stderr=subprocess.PIPE, shell=shell)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'elm-oracle'
```

**Comment by deadfoxygrandpa** [comment]
This is not normal. I will look into this for you. If I have some more questions, would you mind enabling debug logging and helping me troubleshoot?
